services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chess-timer
      - PORT=5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend # Mount local backend code for development
      - /app/backend/node_modules # Don't mount local node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 